### PR TITLE
 Fixes for 0.7/1.0

### PR DESCRIPTION
**Pull request by tkoolen**

### CODE REVIEW

**Comment by piever** [comment]
Thanks! Failures may be due to WebIO and Blink not working on julia 0.7 yet, did you get this to pass test locally on Julia 0.7?

**Comment by tkoolen** [comment]
Yeah, tests pass locally on 1.0 with no deprecations with:

* [ ] https://github.com/JunoLab/Blink.jl/pull/139
* [ ] https://github.com/JuliaGizmos/JSExpr.jl/pull/16
* [x] Mustache tag: https://github.com/JuliaLang/METADATA.jl/pull/16846
* [ ] https://github.com/JuliaWeb/Mux.jl/pull/66
* [x] https://github.com/vtjnash/Pidfile.jl/pull/2: https://github.com/JuliaLang/METADATA.jl/pull/16851
* [ ] https://github.com/JuliaGizmos/WebIO.jl/pull/169
* [x] WebSockets master: https://github.com/JuliaLang/METADATA.jl/pull/16844

**Comment by piever** [comment]
Perfect, I'll merge as is and will come back to do some clean up when there is a new WebIO release.

**Comment by tkoolen** [comment]
Sounds good, thanks!

**Pull request merged**
